### ISSUE TITLE
Add this to  Spicetify Extension

### ISSUE THREAD

**Issue by GildasEdraE** [dupitydumb/LyricsPlus-Spotify#2]
If you Add this to Spicetify, It's gonna be good

**Comment by dupitydumb** [comment]
Hey! Thank you for the suggestion. It's currently available on Spicetify, you can download it through the marketplace. but the feature is limited, you cannot customize the color of the background. it automatically changes based on the song that plays

### How its look
![image](https://github.com/dupitydumb/LyricsPlus-Spotify/assets/37872714/4165ad25-5cdd-497f-827e-d01d9b175a5b)

### Install through Marketplace
![image](https://github.com/dupitydumb/LyricsPlus-Spotify/assets/37872714/7429ae4e-5cf5-4310-958f-8b346ca835c8)

**Comment by GildasEdraE** [comment]
> Hey! Thank you for the suggestion. It's currently available on Spicetify, you can download it through the marketplace. but the feature is limited, you cannot customize the color of the background. it automatically changes based on the song that plays
> 
> ### How its look
> ![image](https://private-user-images.githubusercontent.com/37872714/326159660-4165ad25-5cdd-497f-827e-d01d9b175a5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjY1MjUsIm5iZiI6MTcxNDIyNjIyNSwicGF0aCI6Ii8zNzg3MjcxNC8zMjYxNTk2NjAtNDE2NWFkMjUtNWNkZC00OTdmLTgyN2UtZDAxZDliMTc1YTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzdmOTZmYzQ2OWI1YjI1MDY1MzkxN2VkMTZlODg0MDc4ZGU2ZDk3ZGQ0ZjU4OTc0NGY5ZGQ1MjVhMDVhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k3a_w4mRfWavaaxZ7-C3ZGhhObGrSKnBEbYkyPnIjUc)
> 
> ### Install through Marketplace
> ![image](https://private-user-images.githubusercontent.com/37872714/326159481-7429ae4e-5cf5-4310-958f-8b346ca835c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyMjY1MjUsIm5iZiI6MTcxNDIyNjIyNSwicGF0aCI6Ii8zNzg3MjcxNC8zMjYxNTk0ODEtNzQyOWFlNGUtNWNmNS00MzEwLTk1OGYtOGIzNDZjYTgzNWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDEzNTcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZTczZTBlOTAyNjE1Yzk3OWU3OTFlY2I3ZjYyZDhlOTlkNWE5ZjUwNzI3NTY1YjkzN2U1NjJkMWMyN2RhODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tPzze1LzAJRGlovt9x-dTdGF93Tk2vYhNxxCvvqBtQw)

I knew it, but if you add more feature like chrome extension, It's gonna be good

**Comment by dupitydumb** [comment]
Thank you!, hopefully soon I can integrate the setting into Spicetify!

**Comment by GildasEdraE** [comment]
> Thank you!, hopefully soon I can integrate the setting into Spicetify!

Hopefully it can
