### ISSUE TITLE
Manifest file is invalid / Could not load manifest 

### ISSUE THREAD

**Issue by Minedude33Gaming** [dupitydumb/LyricsPlus-Spotify#6]
When following the instructions to install the Lyrics+ extension, it presents me with this error message. I have checked that indeed the manifest file is spelled correctly and is a JSON file, despite these parameters, the error still persists. It prevents me from finishing the installation properly.
![image](https://github.com/dupitydumb/LyricsPlus-Spotify/assets/58994664/07faee8b-b966-4149-aee5-af087e4bdc0d)

**Comment by dupitydumb** [comment]
for the chrome extension make sure you download the correct file. you can download the [latest release](https://github.com/dupitydumb/LyricsPlus-Spotify/releases/tag/V0.3) or unstable version via this [folder](https://github.com/dupitydumb/LyricsPlus-Spotify/tree/main/LyricsPlus)

**Comment by Minedude33Gaming** [comment]
> for the chrome extension make sure you download the correct file. you can download the [latest release](https://github.com/dupitydumb/LyricsPlus-Spotify/releases/tag/V0.3) or unstable version via this [folder](https://github.com/dupitydumb/LyricsPlus-Spotify/tree/main/LyricsPlus). let me know if its fix

I was able to fix it using the latest version, however moving over to the custom app on Spotify, how in the world do you change the colors correctly?

**Comment by dupitydumb** [comment]
the customization for spicetify is on the way! #7 

> > for the chrome extension make sure you download the correct file. you can download the [latest release](https://github.com/dupitydumb/LyricsPlus-Spotify/releases/tag/V0.3) or unstable version via this [folder](https://github.com/dupitydumb/LyricsPlus-Spotify/tree/main/LyricsPlus). let me know if its fix
> 
> I was able to fix it using the latest version, however moving over to the custom app on Spotify, how in the world do you change the colors correctly?
